feat: refactored tools into rules

diff --git a/tools/lint b/tools/lint
--- a/tools/lint
+++ b/tools/lint
@@ -5,14 +5,25 @@ IFS=$'\n\t'
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 START="$PWD"
 
+CODE=0
+
+if ! "${SCRIPT_DIR}/unaligned-versions"; then
+  CODE=1
+fi
+
 for DIR in  ./packages/*; do
   if [[ -f "${DIR}/package.json" ]]; then
     cd $DIR
     for RULE in $SCRIPT_DIR/rules/*; do
-      if [[ -f $RULE && -x $RULE ]]; then
-        $RULE $@
+      if [[ -f $RULE && -x $RULE ]]; then  
+        if ! $RULE $@; then
+          echo "$(basename $RULE) failed in ${DIR}"
+          CODE=1
+        fi
       fi
     done
     cd $START
   fi
 done
+
+exit $CODE
